### ISSUE TITLE
no matching function

### ISSUE THREAD

**Issue by PEHO70** [gomitone/digitalspinetester#1]
Hi
after check and compiling the digital_spine_tester.ino i got error message in Arduino IDE 1.8.13.
at line.................. **HX711 scale (DOUT, CLK);**

copied error message:

Digital_Spine_Tester:19:22: error: no matching function for call to 'HX711::HX711(int, int)'
 HX711 scale(DOUT, CLK);
                      ^
In file included from D:\TEMP\Dig_Spine\SW\Digital_Spine_Tester\Digital_Spine_Tester.ino:14:0:
C:\Users\_______\Documents\Arduino\libraries\HX711/HX711.h:22:3: note: candidate: HX711::HX711()
   HX711();
   ^~~~~
C:\Users\_______\Documents\Arduino\libraries\HX711/HX711.h:22:3: note:   candidate expects 0 arguments, 2 provided
C:\Users\_______\Documents\Arduino\libraries\HX711/HX711.h:19:7: note: candidate: constexpr HX711::HX711(const HX711&)
 class HX711
       ^~~~~
C:\Users\_______\Documents\Arduino\libraries\HX711/HX711.h:19:7: note:   candidate expects 1 argument, 2 provided
exit status 1
no matching function for call to 'HX711::HX711(int, int)'

Is there any idea what i did wrong ??

**Comment by gomitone** [comment]
Hi,
did you installed all the provided libraries?

**Comment by PEHO70** [comment]
Hi Roberto

 

yes, all linked libraries from the readme-file are installed

 

HX711, onebutton & u8g2..

 

 

 

BR

Peter

 

 

 
 

Gesendet: Mittwoch, 02. September 2020 um 10:16 Uhr
Von: "Roberto Di Pace" <notifications@github.com>
An: "gomitone/digitalspinetester" <digitalspinetester@noreply.github.com>
Cc: "Peter" <schon.mal@abwesend.de>, "Author" <author@noreply.github.com>
Betreff: Re: [gomitone/digitalspinetester] no matching function (#1)


 
Hi,
did you installed all the provided libraries?

**Comment by PEHO70** [comment]
Hi Roberto 
solved this issue byself..

Please find part of the new code...

Deleted **(Dout, CLK)** after HX711 scale and add the initializing command to **setup (void)**....that´s it..



HX711 **scale;**

OneButton buttonTare(4, true);                    //Digital pin 3 for Tare button
OneButton buttonWeight(5, true);                  //Digital pin 4 for Weight button
OneButton buttonSpine(6, true);                   //Digital pin 5 for Spine button

float calibration_factor = 456;                   //Value calculated from calibration of digital scale. Standard values in grams
float baseWeight = 0.0;                           //To store shaft weight
float spineWeight = 0.0;                          //To store weight for spine measurement

U8G2_SSD1306_128X32_UNIVISION_F_HW_I2C u8g2(U8G2_R0); //Initialize the proper oled. See library sample for the correct one.

void setup(void) {
  **scale.begin(DOUT, CLK);**
  u8g2.begin();                                   //Initialize display
  buttonTare.attachClick(click1);                 //-----------------------------------------------
  buttonTare.attachLongPressStop(pressStop1);     //Attach different..
  buttonWeight.attachClick(click2);               //..buttons actions
  buttonSpine.attachClick(click3);                //-----------------------------------------------
}



Feel free to updated your .ino file

BR
PEter

**Comment by gomitone** [comment]
Thanks Peter,
not sure why the code as-is doesn’t work.
But I’m happy you found a solution.
Regards
Roberto

Sent from Mail for Windows 10
